### ISSUE TITLE
MAGICK++ include issue

### ISSUE THREAD

**Issue by thomdabeast** [skyman/homebrew-gt#2]
==> cmake -DENABLE_MAGICK7_SUPPORT=ON .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/nin10kit/1.7 -DCMAKE_BUILD_TYPE=Rel
==> make
Last 15 lines from /Users/thomhemenway/Library/Logs/Homebrew/nin10kit/02.make:
         ^~~~~~~~~~~~
1 error generated.
1 error generated.
make[2]: *** [CMakeFiles/shared_files.dir/shared/gba-exporter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/shared_files.dir/shared/ds-exporter.cpp.o] Error 1
In file included from /tmp/nin10kit-20171228-90292-1utspvs/shared/3ds-exporter.cpp:5:
In file included from /tmp/nin10kit-20171228-90292-1utspvs/shared/export_params.hpp:6:
/tmp/nin10kit-20171228-90292-1utspvs/shared/image32.hpp:4:10: fatal error: 'Magick++.h' file not found
#include <Magick++.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/shared_files.dir/shared/3ds-exporter.cpp.o] Error 1
make[1]: *** [CMakeFiles/shared_files.dir/all] Error 2
make: *** [all] Error 2

**Comment by cgokmen** [comment]
Can you paste the entire homebrew output? Also, what version of OSX is this, and what's the machine?

**Comment by cgokmen** [comment]
Because this version compiles and runs just fine on my '16 MBP with 10.13 on it
