### ISSUE TITLE
'Magick++.h' file not found

### ISSUE THREAD

**Issue by kikush98** [skyman/homebrew-gt#3]
cmake -DENABLE_MAGICK7_SUPPORT=ON .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr
==> make
Last 15 lines from /Users/e_b/Library/Logs/Homebrew/nin10kit/02.make:
         ^~~~~~~~~~~~
1 error generated.
1 error generated.
make[2]: *** [CMakeFiles/shared_files.dir/shared/ds-exporter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/shared_files.dir/shared/gba-exporter.cpp.o] Error 1
In file included from /tmp/nin10kit-20190409-6233-87qx8w/shared/3ds-exporter.cpp:5:
In file included from /tmp/nin10kit-20190409-6233-87qx8w/shared/export_params.hpp:6:
/tmp/nin10kit-20190409-6233-87qx8w/shared/image32.hpp:4:10: fatal error: 'Magick++.h' file not found
#include <Magick++.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/shared_files.dir/shared/3ds-exporter.cpp.o] Error 1
make[1]: *** [CMakeFiles/shared_files.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/skyman/homebrew-gt/issues

**Comment by cgokmen** [comment]
I'm not maintaining this repository anymore, and I'm not too sure how you found it. It is likely a good idea for your TAs to fork this repo into our organization (@zucchini) and maintain it, so please contact them about it.
